### PR TITLE
Make Events class Serializable

### PR DESCRIPTION
**Pull request by visheshruparelia**
**What this PR does / why we need it**:
It makes the Events class Serialiazable. Other classes are already implementing this interface so making this one consistent with others. 

**Special notes for reviewers**:
Corresponding discussion on Slack: https://cloud-native.slack.com/archives/CMBAZQSEP/p1692019690656669

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]
@fjtirado didn't you work on something similar?

**Comment by visheshruparelia** [comment]
@ricardozanini @tsurdilo  would it be possible to release this change as a part of the upcoming release?

**Comment by ricardozanini** [comment]
@visheshruparelia I'll release 4.0.5 first, and then we can add this commit for a follow-up 4.0.6. I didn't want to change the PR now since ppl already tested it. @fjtirado can you also review?

**Comment by visheshruparelia** [comment]
Alright, thank you!

**Comment by fjtirado** [comment]
@ricardozanini good for me

**Comment by ricardozanini** [comment]
@visheshruparelia you can test the main branch on your end.

**Comment by visheshruparelia** [comment]
Sure, by testing you mean evaluate if this fix solved my usecase or do you
mean some sort of regression test?

**Comment by ricardozanini** [comment]
Both would be great! And you can report it back here, please?

**Comment by visheshruparelia** [comment]
Sure, will get back.

**Comment by visheshruparelia** [comment]
@ricardozanini I tested in my local and turns out there were some more classes which needed to be serializable. 
I have raised a PR here: https://github.com/serverlessworkflow/sdk-java/pull/283

**Comment by visheshruparelia** [comment]
We can continue the discussion in that PR if you don't mind. Thanks!

**Pull request merged**
