### PR TITLE
allow to use custom workflow template for generatig diagrams

### PR DESCRIPTION
**Pull request by mswiderski**
Signed-off-by: Maciej Swiderski <swiderski.maciej@gmail.com>

**Many thanks for submitting your Pull Request :heart:!**

**What this PR does / why we need it**:
allows to use custom template for generating diagrams

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Review by tsurdilo — APPROVED** [review]

**Comment by tsurdilo** [comment]
@mswiderski very nice thanks! Would rock to also add something about this in the main readme. Let me know if you can add that to this PR or we should add in a separate one.

**Comment by mswiderski** [comment]
@tsurdilo sure thing, will add some hints about this into the readme file, will try today or latest tomorrow morning.

**Comment by mswiderski** [comment]
@tsurdilo readme file updated, let me know what you think about the text there.

**Review by tsurdilo — APPROVED** [review]

**Comment by tsurdilo** [comment]
@mswiderski lgtm - thank you

**Pull request merged**
