### PR TITLE
Sync branch 4.0.x with main to release 4.0.5

### PR DESCRIPTION
**Pull request by ricardozanini**
**Many thanks for submitting your Pull Request :heart:!**

**What this PR does / why we need it**:
This PR syncs the changes we made in the main to 4.0.x branch to keep the branch clean for the last fix/CVE upgrades.
This is a tentative to run on Java 1.8. It's possible that we might need to do a few adjustments.

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Comment by ricardozanini** [comment]
@manick02 @cdavernas I brought everything from the latest 4.0.4 release. The changes are all related to CVEs and a small bug to cope with 0.8.

It's running and compiling fine with Java 1.8 as you can see in the CI.

@visheshruparelia @fjtirado if you wanna test this PR on your end, please.

**Review by manick02 — APPROVED** [review]
Looks good to me

**Review by cdavernas — APPROVED** [review]
Not my AOE, but I trust you @ricardozanini

@tsurdilo care to take a look?

**Comment by ricardozanini** [comment]
Including the PR to keep the Workflow constructor the same as we have in 4.0.4 to not break the API.

**Pull request merged**
